// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// shifter //
// ------- //

#define shifter_wrap_target 0
#define shifter_wrap 14

#define shifter_BCM_DEPTH 10

#define shifter_offset_upperShift 0u
#define shifter_offset_lowerShift 7u

static const uint16_t shifter_program_instructions[] = {
            //     .wrap_target
    0x80e0, //  0: pull   ifempty block              
    0x40e1, //  1: in     osr, 1                     
    0x606a, //  2: out    null, 10                   
    0x40e1, //  3: in     osr, 1                     
    0x606a, //  4: out    null, 10                   
    0x40e1, //  5: in     osr, 1                     
    0x6060, //  6: out    null, 32                   
    0x80e0, //  7: pull   ifempty block              
    0x40e1, //  8: in     osr, 1                     
    0x606a, //  9: out    null, 10                   
    0x40e1, // 10: in     osr, 1                     
    0x606a, // 11: out    null, 10                   
    0x40e1, // 12: in     osr, 1                     
    0x6060, // 13: out    null, 32                   
    0x8060, // 14: push   iffull block               
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program shifter_program = {
    .instructions = shifter_program_instructions,
    .length = 15,
    .origin = -1,
};

static inline pio_sm_config shifter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + shifter_wrap_target, offset + shifter_wrap);
    return c;
}
#endif

