// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// shifter //
// ------- //

#define shifter_wrap_target 0
#define shifter_wrap 1

static const uint16_t shifter_program_instructions[] = {
            //     .wrap_target
    0x6002, //  0: out    pins, 2                    
    0xc024, //  1: irq    wait 4                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program shifter_program = {
    .instructions = shifter_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config shifter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + shifter_wrap_target, offset + shifter_wrap);
    return c;
}
#endif

// ------ //
// dumper //
// ------ //

#define dumper_wrap_target 2
#define dumper_wrap 5

#define dumper_SYNC_IRQ 0

static const uint16_t dumper_program_instructions[] = {
    0x80e0, //  0: pull   ifempty block   side 0     
    0x6020, //  1: out    x, 32           side 0     
            //     .wrap_target
    0xa041, //  2: mov    y, x            side 0     
    0xc044, //  3: irq    clear 4         side 0     
    0x1083, //  4: jmp    y--, 3          side 1     
    0xc020, //  5: irq    wait 0          side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dumper_program = {
    .instructions = dumper_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config dumper_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dumper_wrap_target, offset + dumper_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

