// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// shifter //
// ------- //

#define shifter_wrap_target 0
#define shifter_wrap 7

#define shifter_offset_loop 1u

static const uint16_t shifter_program_instructions[] = {
            //     .wrap_target
    0xe026, //  0: set    x, 6            side 0     
    0xa042, //  1: nop                    side 0     
    0x40e1, //  2: in     osr, 1          side 0     
    0x80a0, //  3: pull   block           side 0     
    0x0041, //  4: jmp    x--, 1          side 0     
    0x407a, //  5: in     null, 26        side 0     
    0xa016, //  6: mov    pins, ::isr     side 0     
    0xb042, //  7: nop                    side 1     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program shifter_program = {
    .instructions = shifter_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config shifter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + shifter_wrap_target, offset + shifter_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

