// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// pulser //
// ------ //

#define pulser_wrap_target 0
#define pulser_wrap 10

#define pulser_BCM_DEPTH 10
#define pulser_SHIFT_DONE_IRQ 4
#define pulser_SHIFT_TRIG_IRQ 5

static const uint16_t pulser_program_instructions[] = {
            //     .wrap_target
    0x90e0, //  0: pull   ifempty block   side 2     
    0x7040, //  1: out    y, 32           side 2     
    0x70c0, //  2: out    isr, 32         side 2     
    0x90e0, //  3: pull   ifempty block   side 2     
    0x7000, //  4: out    pins, 32        side 2     
    0x30c4, //  5: wait   1 irq, 4        side 2     
    0xb842, //  6: nop                    side 3     
    0xd005, //  7: irq    nowait 5        side 2     
    0xb026, //  8: mov    x, isr          side 2     
    0x0049, //  9: jmp    x--, 9          side 0     
    0x1083, // 10: jmp    y--, 3          side 2     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pulser_program = {
    .instructions = pulser_program_instructions,
    .length = 11,
    .origin = -1,
};

static inline pio_sm_config pulser_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pulser_wrap_target, offset + pulser_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

