// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// shifter //
// ------- //

#define shifter_wrap_target 2
#define shifter_wrap 7

#define shifter_SHIFT_TRIG_IRQ 0
#define shifter_SHIFT_DONE_IRQ 1

static const uint16_t shifter_program_instructions[] = {
    0x80e0, //  0: pull   ifempty block   side 0     
    0x60c0, //  1: out    isr, 32         side 0     
            //     .wrap_target
    0xa046, //  2: mov    y, isr          side 0     
    0x6008, //  3: out    pins, 8         side 0     
    0x1083, //  4: jmp    y--, 3          side 1     
    0xa003, //  5: mov    pins, null      side 0     
    0xc001, //  6: irq    nowait 1        side 0     
    0x20c0, //  7: wait   1 irq, 0        side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program shifter_program = {
    .instructions = shifter_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config shifter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + shifter_wrap_target, offset + shifter_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

