// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// shifter //
// ------- //

#define shifter_wrap_target 2
#define shifter_wrap 20

#define shifter_BCM_DEPTH 10
#define shifter_SHIFT_DONE_IRQ 4
#define shifter_SHIFT_TRIG_IRQ 5

#define shifter_offset_upperShift 3u
#define shifter_offset_lowerShift 10u

static const uint16_t shifter_program_instructions[] = {
    0x90e0, //  0: pull   ifempty block   side 0     
    0x6040, //  1: out    y, 32                      
            //     .wrap_target
    0xb022, //  2: mov    x, y            side 0     
    0x80a0, //  3: pull   block                      
    0x50e1, //  4: in     osr, 1          side 0     
    0x606a, //  5: out    null, 10                   
    0x40e1, //  6: in     osr, 1                     
    0x606a, //  7: out    null, 10                   
    0x40e1, //  8: in     osr, 1                     
    0x6060, //  9: out    null, 32                   
    0x80a0, // 10: pull   block                      
    0x58e1, // 11: in     osr, 1          side 1     
    0x606a, // 12: out    null, 10                   
    0x40e1, // 13: in     osr, 1                     
    0x606a, // 14: out    null, 10                   
    0x40e1, // 15: in     osr, 1                     
    0x6060, // 16: out    null, 32                   
    0xb806, // 17: mov    pins, isr       side 1     
    0x0043, // 18: jmp    x--, 3                     
    0xd004, // 19: irq    nowait 4        side 0     
    0x30c5, // 20: wait   1 irq, 5        side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program shifter_program = {
    .instructions = shifter_program_instructions,
    .length = 21,
    .origin = -1,
};

static inline pio_sm_config shifter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + shifter_wrap_target, offset + shifter_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

